### ISSUE TITLE
React-Script Upgrade - Registration Repo

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend-registration#123]
### Summary

Upgrade portal-registration to new react-script

### Details

For react-scripts 5.0.1 no new versions are provided since two years https://www.npmjs.com/package/react-scripts

This is a high maintenance and security issues as portal frontend and registration app are heavily reliant on it and library has lots of dependencies.

 

#### Linked Tickets

- Portal https://github.com/eclipse-tractusx/portal-frontend/issues/537 
- Shared-Components https://github.com/eclipse-tractusx/portal-shared-components/issues/100

**Comment by evegufy** [comment]
not quite finished yet, screenshot from rc env:
![image](https://github.com/eclipse-tractusx/portal-frontend-registration/assets/46191613/3a0c4912-77e5-48c2-88bd-fa5842dbf951)
@oyo is informed and takes care of the fix
