### ISSUE TITLE
Company Data Unique Identifier - Update Unique Identifier Regex

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend-registration#190]
## Description

The current implementation of the regex for the unique identifier worldwide data input allows for spaces at the beginning, the end, as well as multiple spaces in between. This needs to be updated to only allow a single space in between, and not at the start or end of the input.

Implementation to be done under following section: https://github.com/eclipse-tractusx/portal-frontend-registration/blob/main/src/helpers/utils.ts  (note this is the open source file - ideally the change is done inside the cofinity repo first and contributed back to open source)

 

## Tasks

- Review the current regex implementation for the unique identifier input.
- Update the regex to meet the new requirements:
  - Only allow a single space in between characters
  - Do not allow spaces at the beginning or end of the input
- Update the frontend code to use the new regex.
- Thoroughly test the new regex implementation to ensure it works as expected.
- Document the changes in the codebase and update any relevant documentation.

 

## Acceptance Criteria

- The updated regex only allows a single space in between characters in the unique identifier input.
- Spaces are not allowed at the beginning or end of the input.
- The frontend implementation uses the updated regex.
- All tests pass, and the feature works as expected.
- Documentation is updated to reflect the changes.

 
…while implementing the change, please add unit tests

**Comment by MaximilianHauer** [comment]
story should be enhanced to ensure that furthermore 
* only digits are allowed after the initial space 
* Sequence can only start by HRA or HRB
