### ISSUE TITLE
Registration | Company roles does not get updated on Role selection, Verification screen.

### ISSUE THREAD

**Issue by shubhamv-ss** [eclipse-tractusx/portal-frontend-registration#212]
### Current Behavior

- Company roles data is not being updated correctly on the verification and role selection screens.

### Expected Behavior

- Company roles data should be synchronized and updated correctly on both steps.

### Steps To Reproduce

- Initiate a company registration flow
- Skip adding Company Role(s) and proceed next
- The submit button remains disabled on the Verification screen 
- Navigate back to company roles and select all the roles
- Navigate to the verification screen
- Navigate again to company roles and deselect any two roles
- Proceed to the verification screen and check ACTIVE Roles
- Navigate again to company roles and you won't see the lastly selected roles.

**Comment by shubhamv-ss** [comment]
Hi @evegufy ,
Please review and close issue if resolved.
Thanks!

**Comment by evegufy** [comment]
looks fine, thanks!
