### ISSUE TITLE
The system returns a 409 error when a registration is submitted without specifying a Company role.

### ISSUE THREAD

**Issue by shubhamv-ss** [eclipse-tractusx/portal-frontend-registration#227]
### Current Behavior

- Since there is no proper validation on Company roles and Upload docs screen which lets the user proceed without specifying Company role(s). 

### Expected Behavior

- Ideally, validation should trigger on the Company Role screen and on Upload documents screen instead of the Verification screen by making the “Confirm“ button disabled.
- Or even better, we can disable the next/submit button on these two steps until the user selects roles and uploads docs.

### Steps To Reproduce

- Initiate Registration process
- Skip specifying Company role
- On the verification screen, hit submit (if the button is enabled, else go back to the company role screen select & deselect the Company role)
- Navigate to the Verification screen and hit the Submit button

**Comment by jjeroch** [comment]
ticket not up to date - no assignee, no prioritization
