### ISSUE TITLE
Registration | Upload Document : Error msg always display on screen even if no doc uploaded.

### ISSUE THREAD

**Issue by shubhamv-ss** [eclipse-tractusx/portal-frontend-registration#229]
### Current Behavior

- An error message appears on the Upload Document section even when no document is uploaded.
![image](https://github.com/user-attachments/assets/1d14f144-97b2-425e-a91b-c819b2fc6a0c)

### Expected Behavior

- Error should display only if the validation for the uploaded document failed.

### Steps To Reproduce

- Invite the user for registration
- Complete step one
- Move to step 4
- Notice the error message, it is always there.
- If the validation for uploaded docs fails, the user will have 2 error messages.

**Comment by jjeroch** [comment]
Please add an screenshot to ensure that there is no missunderstanding. We have error below the upload document component as well as popups. I guess you are talking about the 1st scenario. Please confirm with a small screenshot and the env. which you used for testing

**Comment by shubhamv-ss** [comment]
> Please add an screenshot to ensure that there is no misunderstanding. We have error below the upload document component as well as popups. I guess you are talking about the 1st scenario. Please confirm with a small screenshot and the env. which you used for testing
> 
> Additionally: if contributing with the fix, make sure that you automatically directly assign the ticket to yourself - otherwise its hard to manage the tickets

Hey @jjeroch ,
I've added the screenshot for this issue.
