### ISSUE TITLE
Registration | No error/warning message on VAT ID with trailing space.

### ISSUE THREAD

**Issue by shubhamv-ss** [eclipse-tractusx/portal-frontend-registration#239]
### Current Behavior

- Registration | No error/warning message on VAT ID with trailing space

### Expected Behavior

- System should generate warning message for trailing spaces.

### Steps To Reproduce

- Login to the Portal Development as CX-admin
- Invite a Business Partner
- Accept invite as invited user
- Start the registration
- Add all other required data
- Add VAT ID with space e.g:  "DE841338373  “
- Complete and submit the registration

**Comment by typecastcloud** [comment]
I'm closing this with agreement of @shubhamv-ss
